### ISSUE TITLE
wavelet_linear

### ISSUE THREAD

**Issue by urja02** [v0lta/PyTorch-Wavelet-Toolbox#37]
does the wavelet linear layer in the network compression perform wavelet transformation of each image being passed into it?
i want to fit a unit into a cnn such that it gives a wavelet transform as the output,but i cant figure out how im supposed to do that.

**Comment by v0lta** [comment]
Dear @urja02,
The wavelet-linear layer is meant as a sparse replacement for a final dense linear layer in CNN. It does not produce a wavelet-like output. Instead, it uses the analysis and synthesis wavelet transform as a learnable basis representation and learns a diagonal weight matrix within that basis. You can read more about that project at https://arxiv.org/pdf/2004.09569v3.pdf .
If you are looking for links between CNN and wavelets it is probably best to look at the wavelet packet transform.
The packet transform stacks fixed filter convolutions like CNN. Since the filters are fixed and we know the low and high-pass parts the results are interpretable.
We have used the packet transform to identify deepfakes in https://arxiv.org/pdf/2106.09369.pdf .
You can look at the code for the model here:
https://github.com/gan-police/frequency-forensics/blob/830c5ff6240e79e81c0446de11e4336856ec99b0/src/freqdect/models.py#L39
It runs on packets which are precomputed here:
https://github.com/gan-police/frequency-forensics/blob/830c5ff6240e79e81c0446de11e4336856ec99b0/src/freqdect/wavelet_math.py#L100

I am not sure if this answered your question. Are you interested in an adaptive wavelet transform for image processing purposes?

**Comment by urja02** [comment]
thank you so much for the reply. Yes i was looking at wavelet transform, to add the layer to an object detection model.
i am interested in a wavelet transform unit for image processing.
 i will look at the deepfakes code.Does the packet transform output the wavelet transform?

**Comment by v0lta** [comment]
Dear @urja02,
Multiple variants of the wavelet transforms, such as the continuous-, packet- or classic-transform exist. The choice depends on the nature of your problem. Usually, the 2d-Haar wavelet transform is a good starting point ( https://pytorch-wavelet-toolbox.readthedocs.io/en/latest/ptwt.html#ptwt.conv_transform_2.wavedec2 ). However, if you are planning to run the coefficients through some kind of a classifier, then the packet approach may be best suited to your needs.

**Comment by urja02** [comment]
thank you so much ill read up more on this!! i was looking at discrete wavelet transform
